### ISSUE TITLE
Please add moduleName variable

### ISSUE THREAD

**Issue by azizautogravity** [mabdurrahman/custom-title-plugin#1]
Please add moduleName variable to use in templates

**Comment by mabdurrahman** [comment]
@azizautogravity Sorry for the delay, I will schedule this feature very soon, but if you have any idea how to get info about VirtualFile's Module OR even getting active Module from a Project instance please share with me... anyway, I appreciated your contribution and your interest in the plugin :)

**Comment by mabdurrahman** [comment]
@azizautogravity Required feature added, just need a couple of hours to be approved by IntelliJ team

**Comment by azizautogravity** [comment]
@mabdurrahman thank you!

**Comment by mabdurrahman** [comment]
sure, you're welcome!
